[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "django-advanced-modals"
version = "1.0.2"
authors = [{name = "Ian Jones", email = "ian@cobi.co.uk"}]
maintainers = [{name = "Thomas Turner"}]
description = "Django app to implement Bootstrap nested modals"
readme = "readme.md"
requires-python = ">=3.6"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "ajax-advanced-helpers>=1.0.0",
    "django-advanced-menus>=1.0.0",
    "django-crispy-forms",
    "make-html",
]

[project.urls]
Homepage = "https://github.com/django-advance-utils/django-advanced-modals"
Upstream = "https://github.com/jonesim/django-modals"

[tool.setuptools.packages.find]
include = ["django_modals*"]

[tool.setuptools.package-data]
django_modals = ["**/*"]

[tool.setuptools.exclude-package-data]
django_modals = ["*.pyc", "*.pyo", "__pycache__"]
